# Generated by Django 4.2.5 on 2023-09-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='science',
        ),
        migrations.RemoveField(
            model_name='video',
            name='science',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Science',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
