# Generated by Django 4.2.5 on 2023-09-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0002_remove_teacher_science_remove_video_science_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('level', models.CharField(max_length=50)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.science')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=500)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.science')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('pptx_file', models.FileField(upload_to='pptx_file')),
                ('type', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.teacher')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.science')),
            ],
        ),
    ]
